supfiles_extranet/config/routes.rb
Rails.application.routes.draw do
  resources :single_files
  resources :repositories
  devise_for :users
  resources :users

  get '/', to: redirect('/repositories/1')
end

supfiles_extranet/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

supfiles_extranet/app/models/repository.rb
class Repository < ApplicationRecord
  belongs_to :repository
  has_many :repositories, dependent: :destroy
  has_many :single_files, dependent: :destroy

  def breadcrumbs_trail
    repository = self
    breadcrumbs_trail = [repository]
    # while !node.id.eql?(1) && node.meeting.eql?(nil) do
    until repository.id.eql?(1) do
      breadcrumbs_trail.prepend(repository.repository)
      repository = repository.repository
    end
    breadcrumbs_trail
  end
end

supfiles_extranet/app/models/single_file.rb
class SingleFile < ApplicationRecord
  belongs_to :repository
  has_attached_file :file_file
  do_not_validate_attachment_file_type :file_file
end

supfiles_extranet/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

supfiles_extranet/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

supfiles_extranet/app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_repository, only: [:edit, :update, :destroy]

  # GET /repositories
  # GET /repositories.json
  def index
    @repositories = Repository.all
  end

  # GET /repositories/1
  # GET /repositories/1.json
  def show
    @current_repository = Repository.find(params[:id])
  end

  # GET /repositories/new
  def new
    @repository = Repository.new
  end

  # GET /repositories/1/edit
  def edit
  end

  # POST /repositories
  # POST /repositories.json
  def create
    @repository = Repository.new(repository_params)

    respond_to do |format|
      if @repository.save
        format.html { redirect_to @repository, notice: 'Repository was successfully created.' }
        format.json { render :show, status: :created, location: @repository }
      else
        format.html { render :new }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repositories/1
  # PATCH/PUT /repositories/1.json
  def update
    respond_to do |format|
      if @repository.update(repository_params)
        format.html { redirect_to @repository, notice: 'Repository was successfully updated.' }
        format.json { render :show, status: :ok, location: @repository }
      else
        format.html { render :edit }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repositories/1
  # DELETE /repositories/1.json
  def destroy
    @repository.destroy
    respond_to do |format|
      format.html { redirect_to repositories_url, notice: 'Repository was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_repository
    @repository = Repository.find(params[:id])
  end

  def repository_params
    params.require(:repository).permit(:name, :repository_id)
  end
end

supfiles_extranet/app/controllers/single_files_controller.rb
class SingleFilesController < ApplicationController
  before_action :set_single_file, only: [:show, :edit, :update, :destroy]

  # GET /single_files
  # GET /single_files.json
  def index
    @single_files = SingleFile.all
  end

  # GET /single_files/1
  # GET /single_files/1.json
  def show
  end

  # GET /single_files/new
  def new
    @single_file = SingleFile.new
  end

  # GET /single_files/1/edit
  def edit
  end

  # POST /single_files
  # POST /single_files.json
  def create
    @single_file = SingleFile.new(single_file_params)

    respond_to do |format|
      if @single_file.save
        format.html { redirect_to @single_file.repository, notice: 'Single file was successfully created.' }
        format.json { render :show, status: :created, location: @single_file }
      else
        format.html { render :new }
        format.json { render json: @single_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /single_files/1
  # PATCH/PUT /single_files/1.json
  def update
    respond_to do |format|
      if @single_file.update(single_file_params)
        format.html { redirect_to @single_file, notice: 'Single file was successfully updated.' }
        format.json { render :show, status: :ok, location: @single_file }
      else
        format.html { render :edit }
        format.json { render json: @single_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /single_files/1
  # DELETE /single_files/1.json
  def destroy
    repository = @single_file.repository
    @single_file.destroy
    respond_to do |format|
      format.html { redirect_to repository, notice: 'Single file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_single_file
    @single_file = SingleFile.find(params[:id])
  end

  def single_file_params
    params.each { |pa| p pa}
    params.require(:single_file).permit(:name, :repository_id, :file_file)
  end
end

supfiles_extranet/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstname, :lastname)
    end
end

supfiles_extranet/app/helpers/application_helper.rb
module ApplicationHelper
end

supfiles_extranet/app/helpers/repositories_helper.rb
module RepositoriesHelper
end

supfiles_extranet/app/helpers/single_files_helper.rb
module SingleFilesHelper
end

supfiles_extranet/app/helpers/users_helper.rb
module UsersHelper
end

supfiles_extranet/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SupfilesExtranet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

supfiles_extranet/app/views/repositories/_form.html.haml
= form_for @repository do |f|
  - if @repository.errors.any?
    #error_explanation
      %h2= "#{pluralize(@repository.errors.count, "error")} prohibited this repository from being saved:"
      %ul
        - @repository.errors.full_messages.each do |message|
          %li= message

  .field{style: params[:controller].eql?('repositories') ? 'display:none;' : ''}
    = f.select :repository, Repository.all.map { |r| [r.name, r.id] }
  .field
    = f.text_field :name
    = f.submit 'Enregisrter'

supfiles_extranet/app/views/repositories/edit.html.haml
%h1 Editing repository

= render 'form'

= link_to 'Show', @repository
\|
= link_to 'Back', repositories_path

supfiles_extranet/app/views/repositories/index.html.haml
%h1 Listing repositories

%table
  %thead
    %tr
      %th Name
      %th Repository
      %th
      %th
      %th

  %tbody
    - @repositories.each do |repository|
      %tr
        %td= repository.name
        %td= repository.repository
        %td= link_to 'Show', repository
        %td= link_to 'Edit', edit_repository_path(repository)
        %td= link_to 'Destroy', repository, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Repository', new_repository_path

supfiles_extranet/app/views/repositories/new.html.haml
%h1 New repository

= render 'form'

= link_to 'Back', repositories_path

supfiles_extranet/app/views/repositories/show.html.haml
%h1 Listing repositories
%h2= "size/30Go"

- @current_repository.breadcrumbs_trail.each do |repo|
  = link_to repo.name, repo
  = ' > '

%table
  %thead
    %tr
      %th Nom
      %th
      %th
      %th

  %tbody
    - @current_repository.repositories.each do |repository|
      %tr
        %td= repository.name
        %td= link_to 'Parcourir', repository
        %td= link_to 'Editer', edit_repository_path(repository)
        %td= link_to 'Supprimer', repository, method: :delete, data: { confirm: 'Are you sure?' }
    - @current_repository.single_files.each do |file|
      %tr
        %td= file.name
        %td= link_to 'Télécharger', file.file_file.url
        %td{colspan:2}= link_to 'Supprimer', file, method: :delete, data: { confirm: 'Are you sure?' }

%br

Ajouter un nouveau fichier
- @repository = Repository.new(repository: @current_repository)
= render 'repositories/form'

Ajouter un nouveau fichier
- @single_file = SingleFile.new(repository: @current_repositories) unless defined?(@single_file)
= render 'single_files/form'

supfiles_extranet/app/views/single_files/_form.html.haml
= form_for @single_file do |f|
  - if @single_file.errors.any?
    #error_explanation
      %h2= "#{pluralize(@single_file.errors.count, "error")} prohibited this single_file from being saved:"
      %ul
        - @single_file.errors.full_messages.each do |message|
          %li= message


  .field{style: params[:controller].eql?('repositories') ? 'display:none;' : ''}
    = f.select :repository_id, Repository.all.map { |r| [r.name, r.id] }
  .field
    = f.text_field :name
    = f.file_field :file_file
    = f.submit 'Envoyer'

supfiles_extranet/app/views/single_files/edit.html.haml
%h1 Editing single_file

= render 'form'

= link_to 'Show', @single_file
\|
= link_to 'Back', single_files_path

supfiles_extranet/app/views/single_files/index.html.haml
%h1 Listing single_files

%table
  %thead
    %tr
      %th Name
      %th Repository
      %th
      %th
      %th

  %tbody
    - @single_files.each do |single_file|
      %tr
        %td= single_file.name
        %td= single_file.repository
        %td= link_to 'Show', single_file
        %td= link_to 'Edit', edit_single_file_path(single_file)
        %td= link_to 'Destroy', single_file, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Single file', new_single_file_path

supfiles_extranet/app/views/single_files/new.html.haml
%h1 New single_file

= render 'form'

= link_to 'Back', single_files_path

supfiles_extranet/app/views/single_files/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @single_file.name
%p
  %b Repository:
  = @single_file.repository

= link_to 'Edit', edit_single_file_path(@single_file)
\|
= link_to 'Back', single_files_path

supfiles_extranet/app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :firstname
    = f.text_field :firstname
  .field
    = f.label :lastname
    = f.text_field :lastname
  .actions
    = f.submit 'Save'

supfiles_extranet/app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

supfiles_extranet/app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Firstname
      %th Lastname
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.firstname
        %td= user.lastname
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User', new_user_path

supfiles_extranet/app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

supfiles_extranet/app/views/users/show.html.haml
%p#notice= notice

%p
  %b Firstname:
  = @user.firstname
%p
  %b Lastname:
  = @user.lastname

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path